# SPDX-License-Identifier: MPL-2.0
"""Bounded deterministic log recipe; the unique marker crosses a page/scan boundary."""
import hashlib
import json

SIZE = 512 * 1024 * 1024
OFFSET = 8 * 1024 * 1024 - 4
NEEDLE = 'BOUNDARY_MATCH_🧪'
APPEND = 'TAIL_APPEND_SENTINEL\n'
ROTATED = 'ROTATED_SENTINEL\n'
BLOCK = (b'0123456789abcdef' * 3 + b'0123456789abcde\n') * 1024


def generate(path, size=SIZE, offset=OFFSET):
    marker = NEEDLE.encode()
    if size < 4096 or not 0 <= offset <= size - len(marker): raise ValueError('Invalid log recipe bounds')
    sha = hashlib.sha256()
    with path.open('xb') as stream:
        for position in range(0, size, len(BLOCK)):
            raw = bytearray(BLOCK[:min(size - position, len(BLOCK))])
            start, end = max(position, offset), min(position + len(raw), offset + len(marker))
            if start < end: raw[start-position:end-position] = marker[start-offset:end-offset]
            stream.write(raw);sha.update(raw)
    return dict(bytes=size, sha256=sha.hexdigest(), needle_offset=offset)


def fixture():
    data = dict(bytes=SIZE, needle_offset=OFFSET, needle=NEEDLE, append=APPEND, rotated=ROTATED,
                private_growth_limit=192 * 1024 * 1024, generation_block_bytes=len(BLOCK))
    data['identity'] = dict(procedure='huge_log_tail-v1', fixture_sha256=hashlib.sha256(json.dumps(data, sort_keys=True, ensure_ascii=False).encode()).hexdigest(), encoding='utf-8', eol='lf')
    return data


def verify_rotated(path, generated):
    """Bind the observed rotated prefix and append to the original generated bytes."""
    size = generated['bytes']
    if type(size) is not int or not 4096 <= size <= SIZE or path.stat().st_size != size + len(APPEND.encode()):
        raise ValueError('Rotated file length differs')
    sha = hashlib.sha256()
    with path.open('rb') as stream:
        remaining = size
        while remaining:
            raw = stream.read(min(65536, remaining))
            if not raw: raise ValueError('Rotated prefix truncated')
            sha.update(raw); remaining -= len(raw)
        if sha.hexdigest() != generated['sha256'] or stream.read(len(APPEND.encode()) + 1) != APPEND.encode():
            raise ValueError('Rotated prefix or appended bytes changed')


def validate_observations(steps, records):
    def check(stage):
        found = [r['details'] for r in records if r.get('stage') == stage]
        if len(found) != 1 or not isinstance(found[0], dict): raise ValueError('Log checkpoint missing/duplicate: ' + stage)
        return found[0]
    status = {r['id']: r['status'] for r in steps}
    if status.get('s1') == 'PASS':
        before, edited, restored = (check(name) for name in ('log initial viewport', 'log edited viewport', 'log Undo viewport'))
        prefix = BLOCK[:64].decode()
        if not before.get('visible', '').startswith(prefix) or not edited.get('visible', '').startswith('X'+prefix) or not restored.get('visible', '').startswith(prefix):
            raise ValueError('Paged viewport edit/Undo differs')
        memory = check('log memory bound')
        if any(type(memory.get(k)) is not int or memory[k] <= 0 for k in ('baseline', 'after')) or memory['after'] - memory['baseline'] > fixture()['private_growth_limit']:
            raise ValueError('Observed editor memory exceeds declared bound')
    if status.get('s2') == 'PASS':
        if check('log complete search').get('name') != 'Find results: 1 matches' or check('log boundary selection').get('selected') != [NEEDLE]:
            raise ValueError('Unique global boundary match was not selected')
    if status.get('s3') == 'PASS':
        if APPEND.strip() not in check('log appended viewport').get('visible', ''): raise ValueError('Appended tail missing')
        if check('log rotated viewport').get('visible') != ROTATED: raise ValueError('Rotated content stale or incorrect')
        if check('log rotation').get('old_bytes') != SIZE + len(APPEND.encode()): raise ValueError('Rotation did not preserve prior file')
