# SPDX-License-Identifier: MPL-2.0
"""Render the native journey readiness ledger and check its inputs (QA-14).

The ledger is generated on demand from tests/e2e/journeys.json (journeys and
their acceptance cases), tests/e2e/quarantine.json and tests/e2e/readiness.json
(acceptance case text and each journey's last native result). It is not kept
in the repository; edit those inputs and render it when you need it.

Usage:
  python tests/e2e/readiness.py render [--out PATH]
                                 write the ledger to PATH (default
                                 target/qa/READINESS.md; "-" for stdout)
  python tests/e2e/readiness.py check
                                 fail if the inputs disagree or the ledger
                                 cannot be rendered
  python tests/e2e/readiness.py record SUMMARY --commit SHA --date YYYY-MM-DD
                                 take last results from a journey_matrix
                                 summary.json into tests/e2e/readiness.json
"""
import argparse
from datetime import date
import json
from pathlib import Path
import sys

import journey_matrix
import runner

ROOT = runner.ROOT
DATA = ROOT / "tests/e2e/readiness.json"
# Git-ignored (/target/): the rendered ledger is never committed.
DEFAULT_LEDGER = ROOT / "target/qa/READINESS.md"
RESULTS = ("PASS", "FLAKY", "FAIL", "NOT_RUN")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def load(path=DATA, manifest_path=journey_matrix.MANIFEST):
    data = runner.read_json(path)
    manifest = runner.manifest(manifest_path)
    require(runner.versioned(data) and isinstance(data.get("cases"), dict) and isinstance(data.get("last_results"), dict),
            "Unsupported readiness data")
    used = {case for row in manifest["journeys"] for case in row["cases"]}
    require(set(data["cases"]) == used, f"Acceptance case text must cover exactly the mapped cases: {sorted(used ^ set(data['cases']))}")
    require(all(isinstance(text, str) and text.strip() for text in data["cases"].values()), "Empty acceptance case text")
    require(set(data["last_results"]) == {row["id"] for row in manifest["journeys"]}, "Every journey needs a last result")
    for journey, row in data["last_results"].items():
        require(isinstance(row, dict) and row.get("result") in RESULTS, f"{journey}: unknown last result")
        ran = row["result"] != "NOT_RUN"
        require(ran == all(row.get(key) for key in ("date", "commit", "attempts")),
                f"{journey}: a native result needs date, commit and attempts; NOT_RUN has none")
        if ran:
            date.fromisoformat(row["date"])
            require(runner.COMMIT.fullmatch(row["commit"]), f"{journey}: full commit required")
    return data, manifest


def status(journey, last, quarantine):
    if journey["tier"] == "vm-only":
        return "VM only: run on a disposable VM with --lab-config; never scheduled"
    if journey["id"] in quarantine:
        entry = quarantine[journey["id"]]
        return f"Quarantined ({entry['ticket']}, since {entry['since']}): {entry['reason']}"
    if last["result"] == "PASS":
        return "Scheduled nightly; failures fail the run"
    return "Scheduled nightly; no native pass recorded"


def render(data, manifest, quarantine):
    lines = ["<!-- Generated by tests/e2e/readiness.py from journeys.json, quarantine.json and readiness.json; do not edit. -->",
             "# Native journey readiness", "",
             "Each native journey, the blueprint acceptance cases it exercises, its last recorded native result",
             "and its status in the scheduled [native-journeys workflow](../../.github/workflows/native-journeys.yml).",
             "A mapping means the journey exercises part of the case on the real Windows UI. A pass is evidence",
             "toward that case; it does not qualify the case on its own, and a result on an older commit says",
             "nothing about the current build.", "",
             "| Journey | Tier | Acceptance cases | Last native result | Status |",
             "| --- | --- | --- | --- | --- |"]
    for journey in manifest["journeys"]:
        last = data["last_results"][journey["id"]]
        result = ("never run" if last["result"] == "NOT_RUN" else
                  f"{last['result']} {last['attempts']} on {last['date']} at `{last['commit'][:12]}`")
        issues = [step["issue"] for step in journey["steps"] if "issue" in step]
        name = f"`{journey['id']}` ({journey['title']})" + (f"; covers {', '.join(issues)}" if issues else "")
        lines.append(f"| {name} | {journey['tier']} | {', '.join(journey['cases'])} | {result} | "
                     f"{status(journey, last, quarantine)} |")
    lines += ["", "## Last result notes", ""]
    for journey in manifest["journeys"]:
        note = data["last_results"][journey["id"]].get("note")
        if note:
            lines.append(f"- `{journey['id']}`: {note}")
    lines += ["", "## Acceptance cases", "", f"Case text from {data['source']}.", "",
              "| Case | Acceptance criterion | Journeys |", "| --- | --- | --- |"]
    for case, text in sorted(data["cases"].items()):
        journeys = [f"`{row['id']}`" for row in manifest["journeys"] if case in row["cases"]]
        lines.append(f"| {case} | {text} | {', '.join(journeys)} |")
    lines += ["", "## Updating", "",
              "- Record a scheduled run: download its `native-journeys-summary` artifact and run",
              "  `python tests/e2e/readiness.py record summary.json --commit <sha> --date <yyyy-mm-dd>`.",
              "- Remove a journey from `tests/e2e/quarantine.json` once it passes three consecutive nightly runs.",
              "- Run `python tests/e2e/readiness.py check` after changing any input; the e2e unit tests run the same checks.",
              "- This ledger is generated on demand with `python tests/e2e/readiness.py render` and is not committed.", ""]
    return "\n".join(lines)


def record(data, summary, commit, day):
    require(runner.COMMIT.fullmatch(commit), "Full commit required")
    date.fromisoformat(day)
    rows = summary.get("journeys") if isinstance(summary, dict) else None
    require(isinstance(rows, dict) and rows, "Summary has no journeys")
    for journey, row in rows.items():
        require(journey in data["last_results"], f"Unknown journey in summary: {journey}")
        result = {"pass": "PASS", "flaky": "FLAKY", "fail": "FAIL"}[row["classification"]]
        classes = {name: count for name, count in row["failure_classes"].items() if count}
        data["last_results"][journey] = {
            "result": result, "date": day, "commit": commit, "attempts": f"{row['passed']}/{row['attempts']}",
            "note": "Scheduled native-journeys run" + (f"; failures by class: {classes}" if classes else "") + "."}
    return data


def check(data_path=DATA, manifest_path=journey_matrix.MANIFEST, quarantine_path=journey_matrix.QUARANTINE):
    """Validate that journeys, quarantine and readiness data agree; return the rendered ledger."""
    data, manifest = load(data_path, manifest_path)
    return render(data, manifest, journey_matrix.load_quarantine(quarantine_path, manifest_path))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="operation", required=True)
    write = sub.add_parser("render")
    write.add_argument("--out", default=str(DEFAULT_LEDGER),
                       help='output path (default target/qa/READINESS.md); "-" writes to standard output')
    sub.add_parser("check")
    update = sub.add_parser("record")
    update.add_argument("summary", type=Path)
    update.add_argument("--commit", required=True)
    update.add_argument("--date", required=True)
    arguments = parser.parse_args(argv)
    try:
        if arguments.operation == "record":
            data, _ = load()
            data = record(data, runner.read_json(arguments.summary), arguments.commit, arguments.date)
            DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
            check()
            print(f"Updated {DATA.relative_to(ROOT).as_posix()}")
            return 0
        text = check()
        if arguments.operation == "check":
            print("Readiness inputs agree: journeys, quarantine, acceptance cases and last results.")
            return 0
        if arguments.out == "-":
            sys.stdout.write(text)
            return 0
        out = Path(arguments.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {out.as_posix()}")
        return 0
    except (ValueError, KeyError, TypeError, OSError) as error:
        print(str(error), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
