[package]
name = "bareline-platform-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bareline-platform = { path = "../platform" }

[dev-dependencies]
winit.workspace = true
bareline-renderer = { path = "../renderer" }
bareline-renderer-recording = { path = "../renderer-recording" }
bareline-ui = { path = "../ui" }

[[example]]
name = "recording_probe_linux"
path = "../platform/recording_probe.rs"

