[package]
name = "bareline-hex-view"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
rust-version.workspace = true
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
bareline-extension-sdk = { path = "../../crates/extension-sdk" }
bareline-first-party-common = { path = "../common" }
