// SPDX-License-Identifier: MPL-2.0
use std::{fmt::Write as _, path::PathBuf};
fn sources(directory: &str) -> Vec<PathBuf> {
    let mut sources: Vec<_> = std::fs::read_dir(directory)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|e| e == "cxx"))
        .collect();
    sources.sort();
    sources
}
fn main() {
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let mut build = cc::Build::new();
    build
        .cpp(true)
        .std("c++17")
        .warnings(false)
        .include("bundled/scintilla/include")
        .include("bundled/lexilla/include")
        .include("bundled/lexilla/lexlib")
        .include(&out)
        .file("src/bridge.cpp");
    build.files(sources("bundled/lexilla/lexlib"));
    // Compile and register the complete upstream lexer set, as upstream Lexilla's
    // generated catalogue does; the bridge resolves modules by their names.
    // LexEDIFACT reads fixed-size headers (GetCharRange of 3 and 9 bytes) without
    // checking the document length. Scintilla ignores such reads silently; the
    // bridge rejects out-of-range reads by design, so that lexer fails on short
    // input. EDIFACT is not in the language catalog, so it stays vendored but is
    // not compiled or registered.
    const EXCLUDED: &[&str] = &["LexEDIFACT.cxx"];
    let lexers: Vec<_> = sources("bundled/lexilla/lexers")
        .into_iter()
        .filter(|path| !path.file_name().is_some_and(|name| EXCLUDED.iter().any(|x| name == *x)))
        .collect();
    let mut modules = Vec::new();
    for path in &lexers {
        let before = modules.len();
        let text = std::fs::read(path).unwrap();
        for line in String::from_utf8_lossy(&text).lines() {
            if let Some(rest) = line.strip_prefix("extern const LexerModule ") {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                assert!(name.starts_with("lm"), "{}: {line}", path.display());
                modules.push(name);
            }
        }
        assert!(modules.len() > before, "{} defines no lexer module", path.display());
    }
    build.files(&lexers);
    let mut header = String::from("// Generated by build.rs from bundled/lexilla/lexers.\n");
    for module in &modules {
        writeln!(header, "extern const Lexilla::LexerModule {module};").unwrap();
    }
    header.push_str("static const Lexilla::LexerModule *const bundledModules[] = {\n");
    for module in &modules {
        writeln!(header, "    &{module},").unwrap();
    }
    header.push_str("};\n");
    std::fs::write(out.join("bareline_lexer_modules.h"), header).unwrap();
    let compiler = build.get_compiler();
    if compiler.is_like_msvc() && !compiler.is_like_clang() {
        // MSVC includes source paths in anonymous-namespace RTTI identifiers.
        // /Brepro alone does not normalize those paths across build roots.
        let root = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        build.flag(format!("/d1trimfile:{root}\\"));
    }
    build.flag_if_supported("/EHsc").compile("bareline_lexilla");
    println!("cargo:rerun-if-changed=src/bridge.cpp");
    println!("cargo:rerun-if-changed=bundled");
}
